### ISSUE TITLE
Error when modified Map

### ISSUE THREAD

**Issue by AlRodA92** [oxwhirl/smac#92] opened 2022-04-18 16:11 UTC
Hi,

I am doing some personal researchs and in order to prove some tasks I need to change or modify the map's terrain (add some walls o high terrain). I have modified some maps, and, regarding the type and number of agents I don't have problems but when I tried to change some terrain features the code gives me the following error

![Error](https://user-images.githubusercontent.com/83612075/163837530-7f9db0ae-263d-4945-9557-0d58dd3d4902.png)

The only modifications I made are elevate some of the terrain so I do not change the size of the map.

Do you know the reason of this error?

Thanks!

**Comment by samvelyan** [comment] 2022-04-18 16:17
Hi @AlRodA92. This is a known issue, which I believe is caused by the mismatch between the versions of Linux SC2 client and Mac/Windows SC2 Editor. I have created an [issue on Blizzard's repo](https://github.com/Blizzard/s2client-proto/issues/185), but there is no update from them I'm afraid.

**Comment by AlRodA92** [comment] 2022-04-18 18:24
Hi @samvelyan, I found this issue https://github.com/deepmind/pysc2/issues/326#issuecomment-873273166 in the DeepMind/Pysc2 repo and works for me. It not a clean solution but at least it is work until other.

Hope it is helps!

**Comment by samvelyan** [comment] 2022-04-18 18:29
Great catch! Thanks for the reference. Closing the issue for now.

**Closed by samvelyan** 2022-04-18 18:29 UTC
